### ISSUE TITLE
Blur doesn't work on tinted color

### ISSUE THREAD

**Issue by nadimalam** [unboxme/Blurberry#1]
Hey,

Firstly, thanks for this library, i was earlier having issues on ios14 and the default blur stopped working for me and i couldn't find a solution to fix it.

Thankfully, with your library it works fine with clear color in the tint: blurEffectView.blur.tintColor = .clear

However, if i change the tint color to any other color i loose the blur and it just gives me a solid background, like screenshot below. Any idea why that could be happening?

![IMG_8EEA77BA2622-1](https://user-images.githubusercontent.com/2089868/94944272-e9f83a80-04d0-11eb-9fc6-4d7d8f0332bb.jpeg)

**Comment by unboxme** [comment]
@nadimalam Thank you for the report. I'll fix it next week.

**Comment by unboxme** [comment]
@nadimalam Sorry for the late reply. I couldn't reproduce the issue. Could you please attach source code or test project?

It seems to be you set a blur like `blurVuew.blur.tintColor = .black`, but the right way is to set a color with alpha component such as `blurVuew.blur.tintColor = UIColor.black.withAlphaComponent(0.25)`.

**Comment by unboxme** [comment]
Closed due to inactivity and lack of issue details.
